---
title: "Untitled"
author: "RN7"
date: "9/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
pacman::p_load(dplyr, tidyr, purrr, stringr, 
               glue, readr,
               rvest, polite, tvthemes,
               ggplot2, scales, ggtext,
               grid, gridExtra)
```


```{r}
main_url <- "https://www.opensubtitles.org/en/ssearch/sublanguageid-eng/idmovie-158594/"

session <- bow(main_url)

all_tabs <- scrape(session) %>%
  html_nodes(xpath = '//*[(@id <- "search_results")]') %>%
  html_table(fill = TRUE)

ep_links <- scrape(session) %>% 
  html_nodes("a") %>% 
  html_attr("href")

ep_titles <- scrape(session) %>% 
  html_nodes("a") %>% 
  html_attr("title")

links_all_raw <- tibble(link = ep_links, 
                        title = ep_titles) 

links_all_clean <- links_all_raw %>% 
  filter(!is.na(title)) %>% 
  distinct(link, .keep_all = TRUE) %>% 
  mutate(link = link %>% 
           str_replace_all(
             "^/en/search/", 
             "https://www.opensubtitles.org/download/s/")) %>% 
  filter(str_detect(link, "imdb")) %>%
  mutate(title = title %>% str_replace_all("\"Brooklyn Nine-Nine\" ", ""),
         season = c(rep("S01", 22), rep("S02", 23), rep("S03", 23),
                    rep("S04", 21), rep("S05", 22), rep("S06", 18)),
         episode = c(1:22, 1:23, 1:23, 
                     1:21, 1:22, 1:18)) %>% 
  mutate(episode = if_else(nchar(episode) == 1, 
                           paste0("E0", episode), 
                           paste0("E", episode)),
         file_name = glue(
           "{season}_{episode}_{str_replace_all(title, '[[:punct:]]', '')}"),
         file_name = str_replace_all(file_name, " ", "_")) %>% 
  select(episode, season, title, file_name, link)

write_csv(links_all_clean,
          path = here::here("data/b99_ep_subtitle_links.csv"))
```



```{r}
links_all_clean <- read_csv(file = here::here("data/b99_ep_subtitle_links.csv"))
```




```{r}
for(j in 1:nrow(links_all_clean)) {
  if(!file.exists(paste0("../data/subtitles/",
                         links_all_clean$file_name[j],
                         ".zip"))) {
    
    Sys.sleep(sample(seq(0.5, 1.5, by = 0.5), 1))
    
    downloader::download(url = links_all_clean$link[j], 
                         destfile = paste0("../data/subtitles/", 
                         links_all_clean$file_name[j],
                         ".zip"), mode = "wb")
  }
}
```



```{r}
library(downloader)


download(url = "https://www.opensubtitles.org/download/s/sublanguageid-eng/imdbid-2936284", destfile = "../data/subtitles/test.zip", mode = "wb")


 unzip("../data/subtitles/test.zip", 
       exdir = "../data/subtitles", overwrite = F)
```


```{r}

links_all_clean <- links_all_clean %>% slice(1:5)

fs::dir_create(here::here("data/subtitles"))

downloadSubtitles <- function(link = link, file_name = file_name) {
  if(!file.exists(here::here(glue::glue("data/subtitles/{file_name}.zip")))) {
    Sys.sleep(5)
    downloader::download(url = link,
                         destfile = here::here(
                           glue::glue("data/subtitles/{file_name}.zip")), 
                         mode = "wb")
    cat("Downloaded", file_name, "!\n")
  }
}

purrr::walk2(links_all_clean$link, links_all_clean$file_name, 
             ~ downloadSubtitles(link = .x, file_name = .y))
```



```{r}
subtitles_zip <- list.files(here::here("data/subtitles/"), 
                            recursive = TRUE) %>% 
  paste0(here::here("data/subtitles/"), .)

fs::dir_create(here::here("data/extracted_subtitles"))

extractSubtitles <- function(zip_link = zip_link, file_name = file_name) {
  if(!file.exists(zip_link)) {
    unzip(zipfile = subtitles_zip,
          exdir = here::here(glue::glue("data/extracted_subtitles/{file_name}")),
          overwrite = FALSE)
    cat("Unzip ", file_name, " Done!\n")
  }
}

purrr::walk2(subtitles_zip, links_all_clean$file_name, 
             ~ extractSubtitles(zip_link = .x, file_name = .y))
```






